desc "build the pdf"
task :default => [] do
  sh "pdflatex -shell-escape model.tex"
  sh "pdfcrop model.pdf"
  sh "pdflatex ein.tex"
  sh "bibtex ein"
  sh "pdflatex ein.tex"
end

task :clean do
  sh "rm -rf *.aux *.bbl *.blg *.log"
end
